# Generated by Django 3.1.3 on 2020-11-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('phno', models.TextField(max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('address', models.TextField()),
                ('capacity', models.TextField()),
                ('city', models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Kolkata', 'Kolkata'), ('Delhi', 'Delhi')], default='Pune', max_length=10)),
                ('cost', models.TextField()),
                ('name', models.CharField(default='Room name', max_length=250)),
                ('description', models.TextField(default='Sample description', max_length=800)),
                ('image', models.ImageField(blank=True, default='images/default_room.jpg', upload_to='images')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default='images/default_room.jpg', upload_to='images/')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
    ]
